#--------------------------------------------------
# Version
#--------------------------------------------------
version: '{build}'  

#--------------------------------------------------
# Branch whitelist
#--------------------------------------------------
branches:
  # Whitelist
  only:
    - master

#--------------------------------------------------
# After cloning repository
#--------------------------------------------------
install:
  - git submodule init
  - git submodule update

#--------------------------------------------------
# Build configuration
#--------------------------------------------------
configuration: Release

#--------------------------------------------------
# Build hooks - before
#--------------------------------------------------
before_build:
  - nuget restore -verbosity detailed
 
#--------------------------------------------------
# Build hooks - after
#--------------------------------------------------
after_build:
   - nuget pack Ofl.Core\Ofl.Core.csproj -verbosity detailed -version {build}
 
#--------------------------------------------------
# NuGet config
#--------------------------------------------------
nuget:
  # disable publishing of .nupkg artifacts to
  # account/project feeds for pull request builds
  disable_publish_on_pr: true
  
#--------------------------------------------------
# Artifact configuration
#--------------------------------------------------
artifacts:  
  - path: '**\*.nupkg'
    name: NuGet
